#!/bin/bash
#This script allows for initial install of software modules
#Author: Stephen J Kennedy
#version 1.0
#DEBUG used with -x (reports shell name, line number, and associated function)
PS4='+ $BASH_SOURCE : $LINENO : ${FUNCNAME[0]} ()'
ADDONLIST="htop vim dnsutils ccze iftop curl openssh-client"

for ADDONS in $ADDONLIST
do 
    echo "apt-get install ${ADDONS}" || exit 1
done
exit 0
